/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'bio.lexicons.temp.occurrence'

export { $nsid }

/** A biodiversity observation record following Darwin Core standards. Represents a single occurrence of an organism. */
type Main = {
  $type: 'bio.lexicons.temp.occurrence'

  /**
   * The date-time when the observation occurred, in ISO 8601 format (Darwin Core dwc:eventDate).
   */
  eventDate?: l.DatetimeString

  /**
   * The geographic latitude in decimal degrees (Darwin Core dwc:decimalLatitude). Valid range: -90 to 90.
   */
  decimalLatitude?: string

  /**
   * The geographic longitude in decimal degrees (Darwin Core dwc:decimalLongitude). Valid range: -180 to 180.
   */
  decimalLongitude?: string

  /**
   * The horizontal distance (in meters) from the given coordinates describing the smallest circle containing the whole of the Location (Darwin Core dwc:coordinateUncertaintyInMeters).
   */
  coordinateUncertaintyInMeters?: number

  /**
   * Strong references to media records documenting the observation (Darwin Core dwc:associatedMedia).
   */
  associatedMedia?: RepoStrongRef.Main[]

  /**
   * Accepted taxon for this occurrence, preferably a stable URI (e.g. a GBIF species URI). Ideally denormalized from the referenced Identification for queryability (sensu DarwinCore dwc:taxonID).
   */
  taxonID?: l.UriString

  /**
   * The Identification record the owner has chosen as the source of taxonID. Should not be present without taxonID (sensu DarwinCore dwc:identificationID).
   */
  identificationID?: l.AtUriString

  /**
   * The SurveyTarget this Occurrence was intended to satisfy. Expresses observer intent.
   */
  surveyTargetID?: l.AtUriString

  /**
   * Event (e.g. a Survey) this Occurrence was a part of (sensu DarwinCore dwc:eventID).
   */
  eventID?: l.AtUriString

  /**
   * The quantity of the organism present at the time of the Occurrence. Generally an integer or float but may be categorical, e.g. 'many' or '10-100' (sensu DarwinCore dwc:organismQuantity).
   */
  organismQuantity?: string

  /**
   * The type of quantification system used for the quantity of organisms (sensu DarwinCore dwc:organismQuantityType).
   */
  organismQuantityType?: string
}

export type { Main }

/** A biodiversity observation record following Darwin Core standards. Represents a single occurrence of an organism. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    eventDate: l.optional(l.string({ format: 'datetime' })),
    decimalLatitude: l.optional(l.string()),
    decimalLongitude: l.optional(l.string()),
    coordinateUncertaintyInMeters: l.optional(l.integer({ minimum: 0 })),
    associatedMedia: l.optional(
      l.array(l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any), {
        maxLength: 10,
      }),
    ),
    taxonID: l.optional(l.string({ format: 'uri' })),
    identificationID: l.optional(l.string({ format: 'at-uri' })),
    surveyTargetID: l.optional(l.string({ format: 'at-uri' })),
    eventID: l.optional(l.string({ format: 'at-uri' })),
    organismQuantity: l.optional(l.string()),
    organismQuantityType: l.optional(l.string()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
