/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtgeoPlace from '../../../org/atgeo/place.defs.js'

const $nsid = 'bio.lexicons.temp.surveyProtocol'

export { $nsid }

/** Defines the contents of a Survey, including what participants should look for and what fields they must fill out. */
type Main = {
  $type: 'bio.lexicons.temp.surveyProtocol'

  /**
   * Name of the protocol (sensu DCMI dc:title).
   */
  title: string

  /**
   * Narrative description of the protocol (sensu DCMI dc:description).
   */
  description: string

  /**
   * Client-declared timestamp when this protocol was originally created.
   */
  createdAt: l.DatetimeString

  /**
   * List of fields required to complete the survey. Known values: 'eventDate', 'eventDuration'.
   */
  requiredFields?: string[]

  /**
   * Pre-selected list of locations where surveys can occur.
   */
  locationOptions?: AtgeoPlace.Main[]
}

export type { Main }

/** Defines the contents of a Survey, including what participants should look for and what fields they must fill out. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    title: l.string(),
    description: l.string(),
    createdAt: l.string({ format: 'datetime' }),
    requiredFields: l.optional(l.array(l.string())),
    locationOptions: l.optional(
      l.array(l.ref<AtgeoPlace.Main>((() => AtgeoPlace.main) as any)),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
