/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as LocationGeo from '../../community/lexicon/location/geo.defs.js'
import * as LocationHthree from '../../community/lexicon/location/hthree.defs.js'
import * as LocationAddress from '../../community/lexicon/location/address.defs.js'
import * as LocationBbox from '../../community/lexicon/location/bbox.defs.js'

const $nsid = 'org.atgeo.place'

export { $nsid }

/** A reference to a related place record. */
type Relation = {
  $type?: 'org.atgeo.place#relation'

  /**
   * Collection-qualified record key (e.g. org.atgeo.places.wof:85922583).
   */
  rkey: l.RecordKeyString

  /**
   * Display name of the related place.
   */
  name?: string

  /**
   * Admin hierarchy level (0=continent, 10=country, 25=region, 50=locality, etc.).
   */
  level?: number
}

export type { Relation }

/** A reference to a related place record. */
const relation = l.typedObject<Relation>(
  $nsid,
  'relation',
  l.object({
    rkey: l.string({ format: 'record-key' }),
    name: l.optional(l.string()),
    level: l.optional(l.integer()),
  }),
)

export { relation }

type Variant = {
  $type?: 'org.atgeo.place#variant'

  /**
   * The variant name text.
   */
  name: string

  /**
   * The kind of variant: official, alternate, short, colloquial, historical.
   */
  type?: string

  /**
   * The language of the name.
   */
  language?: l.LanguageString
}

export type { Variant }

const variant = l.typedObject<Variant>(
  $nsid,
  'variant',
  l.object({
    name: l.string(),
    type: l.optional(l.string()),
    language: l.optional(l.string({ format: 'language' })),
  }),
)

export { variant }

/** A geographic place with location, name, and other attributes. */
type Main = {
  $type: 'org.atgeo.place'

  /**
   * A globally unique identifier for this place record.
   */
  rkey?: l.RecordKeyString

  /**
   * The geographic location of the place, in any available representation.
   */
  locations?: (
    | l.$Typed<LocationGeo.Main>
    | l.$Typed<LocationHthree.Main>
    | l.$Typed<LocationAddress.Main>
    | l.$Typed<LocationBbox.Main>
    | l.Unknown$TypedObject
  )[]

  /**
   * The primary display name of the place.
   */
  name: string

  /**
   * Alternate names, translations, and other name variants.
   */
  variants?: Variant[]

  /**
   * Additional, source-dependent attributes of the place.
   */
  attributes?: l.LexMap

  /**
   * The date when the place record was last updated
   */
  published_at?: l.DatetimeString

  /**
   * Related records, keyed by relation type (within, same_as). Type changed from 'object' to 'unknown' for AT Protocol lexicon spec compatibility; upstream uses a non-standard nested object type.
   */
  relations?: l.LexMap
}

export type { Main }

/** A geographic place with location, name, and other attributes. */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    rkey: l.optional(l.string({ format: 'record-key' })),
    locations: l.optional(
      l.array(
        l.typedUnion(
          [
            l.typedRef<LocationGeo.Main>((() => LocationGeo.main) as any),
            l.typedRef<LocationHthree.Main>((() => LocationHthree.main) as any),
            l.typedRef<LocationAddress.Main>(
              (() => LocationAddress.main) as any,
            ),
            l.typedRef<LocationBbox.Main>((() => LocationBbox.main) as any),
          ],
          false,
        ),
      ),
    ),
    name: l.string(),
    variants: l.optional(l.array(l.ref<Variant>((() => variant) as any))),
    attributes: l.optional(l.lexMap()),
    published_at: l.optional(l.string({ format: 'datetime' })),
    relations: l.optional(l.lexMap()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A reference to a geographic place defined elsewhere. */
type Ref = {
  $type?: 'org.atgeo.place#ref'

  /**
   * An optional reference to a specific version of the place definition.
   */
  cid?: l.CidString

  /**
   * A globally unique identifier for the place.
   */
  id: l.RecordKeyString

  /**
   * The geographic location of the place, in any available representation.
   */
  locations?: (
    | l.$Typed<LocationGeo.Main>
    | l.$Typed<LocationHthree.Main>
    | l.$Typed<LocationAddress.Main>
    | l.$Typed<LocationBbox.Main>
    | l.Unknown$TypedObject
  )[]

  /**
   * The primary display name of the place.
   */
  name?: string

  /**
   * Additional attributes, included for durability or convenience.
   */
  attributes?: l.LexMap

  /**
   * The date when the place record was last updated
   */
  published_at?: l.DatetimeString
}

export type { Ref }

/** A reference to a geographic place defined elsewhere. */
const ref = l.typedObject<Ref>(
  $nsid,
  'ref',
  l.object({
    cid: l.optional(l.string({ format: 'cid' })),
    id: l.string({ format: 'record-key' }),
    locations: l.optional(
      l.array(
        l.typedUnion(
          [
            l.typedRef<LocationGeo.Main>((() => LocationGeo.main) as any),
            l.typedRef<LocationHthree.Main>((() => LocationHthree.main) as any),
            l.typedRef<LocationAddress.Main>(
              (() => LocationAddress.main) as any,
            ),
            l.typedRef<LocationBbox.Main>((() => LocationBbox.main) as any),
          ],
          false,
        ),
      ),
    ),
    name: l.optional(l.string()),
    attributes: l.optional(l.lexMap()),
    published_at: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { ref }
