/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as LocationGeo from '../../community/lexicon/location/geo.defs.js'
import * as LocationHthree from '../../community/lexicon/location/hthree.defs.js'
import * as LocationAddress from '../../community/lexicon/location/address.defs.js'
import * as LocationBbox from '../../community/lexicon/location/bbox.defs.js'

const $nsid = 'org.atgeo.place'

type $nsid = typeof $nsid

export { $nsid }

/** A reference to a related place record. */
type Relation = {
  $type?: 'org.atgeo.place#relation'

  /**
   * Collection-qualified record key (e.g. org.atgeo.places.wof:85922583).
   */
  rkey: l.RecordKeyString

  /**
   * Display name of the related place.
   */
  name?: string

  /**
   * Admin hierarchy level (0=continent, 10=country, 25=region, 50=locality, etc.).
   */
  level?: number
}

export type { Relation }

/** A reference to a related place record. */
const relation = /*#__PURE__*/ l.typedObject<Relation>(
  $nsid,
  'relation',
  /*#__PURE__*/ l.object({
    rkey: /*#__PURE__*/ l.string({ format: 'record-key' }),
    name: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    level: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
  }),
)

export { relation }

type Variant = {
  $type?: 'org.atgeo.place#variant'

  /**
   * The variant name text.
   */
  name: string

  /**
   * The kind of variant: official, alternate, short, colloquial, historical.
   */
  type?: string

  /**
   * The language of the name.
   */
  language?: l.LanguageString
}

export type { Variant }

const variant = /*#__PURE__*/ l.typedObject<Variant>(
  $nsid,
  'variant',
  /*#__PURE__*/ l.object({
    name: /*#__PURE__*/ l.string(),
    type: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    language: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'language' }),
    ),
  }),
)

export { variant }

/** A geographic place with location, name, and other attributes. */
type Main = {
  $type: 'org.atgeo.place'

  /**
   * A globally unique identifier for this place record.
   */
  rkey?: l.RecordKeyString

  /**
   * The geographic location of the place, in any available representation.
   */
  locations?: (
    | l.$Typed<LocationGeo.Main>
    | l.$Typed<LocationHthree.Main>
    | l.$Typed<LocationAddress.Main>
    | l.$Typed<LocationBbox.Main>
    | l.Unknown$TypedObject
  )[]

  /**
   * The primary display name of the place.
   */
  name: string

  /**
   * Alternate names, translations, and other name variants.
   */
  variants?: Variant[]

  /**
   * Additional, source-dependent attributes of the place.
   */
  attributes?: l.LexMap

  /**
   * The date when the place record was last updated
   */
  published_at?: l.DatetimeString

  /**
   * Related records, keyed by relation type (within, same_as). Type changed from 'object' to 'unknown' for AT Protocol lexicon spec compatibility; upstream uses a non-standard nested object type.
   */
  relations?: l.LexMap
}

export type { Main }

/** A geographic place with location, name, and other attributes. */
const main = /*#__PURE__*/ l.record<'any', Main>(
  'any',
  $nsid,
  /*#__PURE__*/ l.object({
    rkey: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'record-key' }),
    ),
    locations: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.typedUnion(
          [
            /*#__PURE__*/ l.typedRef<LocationGeo.Main>(
              (() => LocationGeo.main) as any,
            ),
            /*#__PURE__*/ l.typedRef<LocationHthree.Main>(
              (() => LocationHthree.main) as any,
            ),
            /*#__PURE__*/ l.typedRef<LocationAddress.Main>(
              (() => LocationAddress.main) as any,
            ),
            /*#__PURE__*/ l.typedRef<LocationBbox.Main>(
              (() => LocationBbox.main) as any,
            ),
          ],
          false,
        ),
      ),
    ),
    name: /*#__PURE__*/ l.string(),
    variants: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<Variant>((() => variant) as any),
      ),
    ),
    attributes: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.lexMap()),
    published_at: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
    relations: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.lexMap()),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A reference to a geographic place defined elsewhere. */
type Ref = {
  $type?: 'org.atgeo.place#ref'

  /**
   * An optional reference to a specific version of the place definition.
   */
  cid?: l.CidString

  /**
   * A globally unique identifier for the place.
   */
  id: l.RecordKeyString

  /**
   * The geographic location of the place, in any available representation.
   */
  locations?: (
    | l.$Typed<LocationGeo.Main>
    | l.$Typed<LocationHthree.Main>
    | l.$Typed<LocationAddress.Main>
    | l.$Typed<LocationBbox.Main>
    | l.Unknown$TypedObject
  )[]

  /**
   * The primary display name of the place.
   */
  name?: string

  /**
   * Additional attributes, included for durability or convenience.
   */
  attributes?: l.LexMap

  /**
   * The date when the place record was last updated
   */
  published_at?: l.DatetimeString
}

export type { Ref }

/** A reference to a geographic place defined elsewhere. */
const ref = /*#__PURE__*/ l.typedObject<Ref>(
  $nsid,
  'ref',
  /*#__PURE__*/ l.object({
    cid: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'cid' })),
    id: /*#__PURE__*/ l.string({ format: 'record-key' }),
    locations: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.typedUnion(
          [
            /*#__PURE__*/ l.typedRef<LocationGeo.Main>(
              (() => LocationGeo.main) as any,
            ),
            /*#__PURE__*/ l.typedRef<LocationHthree.Main>(
              (() => LocationHthree.main) as any,
            ),
            /*#__PURE__*/ l.typedRef<LocationAddress.Main>(
              (() => LocationAddress.main) as any,
            ),
            /*#__PURE__*/ l.typedRef<LocationBbox.Main>(
              (() => LocationBbox.main) as any,
            ),
          ],
          false,
        ),
      ),
    ),
    name: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    attributes: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.lexMap()),
    published_at: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
  }),
)

export { ref }
