/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'bio.cuanto.authFull'

type $nsid = typeof $nsid

export { $nsid }

const main = /*#__PURE__*/ l.permissionSet(
  $nsid,
  [
    /*#__PURE__*/ l.permission('repo', {
      collection: [
        'bio.cuanto.survey',
        'bio.cuanto.surveyProtocol',
        'bio.cuanto.surveyProtocol.follow',
        'bio.cuanto.surveyTarget',
      ],
    }),
  ],
  {
    title: 'Full Cuanto.bio access',
    detail:
      'Create and update Cuanto.bio surveys and protocols and follow protocols.',
  },
)

export { main }
