/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'bio.cuanto.protocolTarget'

type $nsid = typeof $nsid

export { $nsid }

/** Subject for surveys following a Protocol. */
type Main = {
  $type: 'bio.cuanto.protocolTarget'

  /**
   * Protocol this target belongs to.
   */
  protocol: l.AtUriString

  /**
   * One or more scope criteria defining what this target is.
   */
  scope: (
    l.$Typed<TaxonScope> | l.$Typed<VerbatimScope> | l.Unknown$TypedObject
  )[]
}

export type { Main }

/** Subject for surveys following a Protocol. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    protocol: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    scope: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<TaxonScope>((() => taxonScope) as any),
          /*#__PURE__*/ l.typedRef<VerbatimScope>((() => verbatimScope) as any),
        ],
        false,
      ),
      { minLength: 1 },
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A taxonomic criterion for a survey target. */
type TaxonScope = {
  $type?: 'bio.cuanto.protocolTarget#taxonScope'

  /**
   * Identifier for the target taxon, preferably a stable URI, e.g. https://www.gbif.org/species/102151594.
   */
  taxonID?: l.UriString

  /**
   * Full scientific name without rank modifiers.
   */
  scientificName: string

  /**
   * Common or vernacular name for the taxon, following dwc:vernacularName. Set by the protocol author as the preferred label shown to surveyors.
   */
  vernacularName?: string

  /**
   * Taxonomic rank, e.g. family, genus, subspecies, variety.
   */
  taxonRank: string

  /**
   * Taxonomic kingdom. Combined with scientificName and taxonRank, provides disambiguation for most homonyms.
   */
  kingdom?: string
}

export type { TaxonScope }

/** A taxonomic criterion for a survey target. */
const taxonScope = /*#__PURE__*/ l.typedObject<TaxonScope>(
  $nsid,
  'taxonScope',
  /*#__PURE__*/ l.object({
    taxonID: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    scientificName: /*#__PURE__*/ l.string(),
    vernacularName: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    taxonRank: /*#__PURE__*/ l.string(),
    kingdom: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  }),
)

export { taxonScope }

/** A free-text criterion for cases not covered by structured types (sensu Humboldt eco:verbatimTargetScope). */
type VerbatimScope = {
  $type?: 'bio.cuanto.protocolTarget#verbatimScope'

  /**
   * Free-text description of what is being targeted, e.g. 'trees > 10 cm DBH'.
   */
  verbatimTargetScope: string
}

export type { VerbatimScope }

/** A free-text criterion for cases not covered by structured types (sensu Humboldt eco:verbatimTargetScope). */
const verbatimScope = /*#__PURE__*/ l.typedObject<VerbatimScope>(
  $nsid,
  'verbatimScope',
  /*#__PURE__*/ l.object({ verbatimTargetScope: /*#__PURE__*/ l.string() }),
)

export { verbatimScope }
