/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'bio.cuanto.protocolTarget'

export { $nsid }

/** Subject for surveys following a Protocol. */
type Main = {
  $type: 'bio.cuanto.protocolTarget'

  /**
   * Protocol this target belongs to.
   */
  protocol: l.AtUriString

  /**
   * One or more scope criteria defining what this target is.
   */
  scope: (
    | l.$Typed<TaxonScope>
    | l.$Typed<VerbatimScope>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

/** Subject for surveys following a Protocol. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    protocol: l.string({ format: 'at-uri' }),
    scope: l.array(
      l.typedUnion(
        [
          l.typedRef<TaxonScope>((() => taxonScope) as any),
          l.typedRef<VerbatimScope>((() => verbatimScope) as any),
        ],
        false,
      ),
      { minLength: 1 },
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A taxonomic criterion for a survey target. */
type TaxonScope = {
  $type?: 'bio.cuanto.protocolTarget#taxonScope'

  /**
   * Identifier for the target taxon, preferably a stable URI, e.g. https://www.gbif.org/species/102151594.
   */
  taxonID?: l.UriString

  /**
   * Full scientific name without rank modifiers.
   */
  scientificName: string

  /**
   * Common or vernacular name for the taxon, following dwc:vernacularName. Set by the protocol author as the preferred label shown to surveyors.
   */
  vernacularName?: string

  /**
   * Taxonomic rank, e.g. family, genus, subspecies, variety.
   */
  taxonRank: string

  /**
   * Taxonomic kingdom. Combined with scientificName and taxonRank, provides disambiguation for most homonyms.
   */
  kingdom?: string
}

export type { TaxonScope }

/** A taxonomic criterion for a survey target. */
const taxonScope = l.typedObject<TaxonScope>(
  $nsid,
  'taxonScope',
  l.object({
    taxonID: l.optional(l.string({ format: 'uri' })),
    scientificName: l.string(),
    vernacularName: l.optional(l.string()),
    taxonRank: l.string(),
    kingdom: l.optional(l.string()),
  }),
)

export { taxonScope }

/** A free-text criterion for cases not covered by structured types (sensu Humboldt eco:verbatimTargetScope). */
type VerbatimScope = {
  $type?: 'bio.cuanto.protocolTarget#verbatimScope'

  /**
   * Free-text description of what is being targeted, e.g. 'trees > 10 cm DBH'.
   */
  verbatimTargetScope: string
}

export type { VerbatimScope }

/** A free-text criterion for cases not covered by structured types (sensu Humboldt eco:verbatimTargetScope). */
const verbatimScope = l.typedObject<VerbatimScope>(
  $nsid,
  'verbatimScope',
  l.object({ verbatimTargetScope: l.string() }),
)

export { verbatimScope }
