/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.js'
import * as AtgeoPlace from '../../org/atgeo/place.defs.js'

const $nsid = 'bio.cuanto.survey'

export { $nsid }

/** An event where participants collect data required by a Survey Protocol. */
type Main = {
  $type: 'bio.cuanto.survey'

  /**
   * Protocol followed when conducting this survey.
   */
  protocol: RepoStrongRef.Main

  /**
   * Client-declared timestamp when this survey was originally created.
   */
  createdAt: l.DatetimeString

  /**
   * DIDs of participants in addition to the record owner (sensu Humboldt eco:samplingPerformedBy).
   */
  samplingPerformedBy?: l.DidString[]

  /**
   * Total number of people conducting the Survey.
   */
  surveyorCount?: number

  /**
   * Date or datetime the survey began, ISO 8601 supporting partial forms (e.g. 2026, 2026-02, 2026-02-03, 2026-02-03T00:01:02Z).
   */
  eventDate?: string

  /**
   * Unit of eventDurationValue (sensu Humboldt eco:eventDurationUnit). Known values: 'minutes', 'hours', 'days'.
   */
  eventDurationUnit?: string

  /**
   * Duration of the survey in units specified by eventDurationUnit (sensu Humboldt eco:eventDurationValue).
   */
  eventDurationValue?: number

  /**
   * Geographic location where the survey was conducted.
   */
  location: AtgeoPlace.Main

  /**
   * A spatial path recorded during the survey.
   */
  track?: Track
}

export type { Main }

/** An event where participants collect data required by a Survey Protocol. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    protocol: l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    createdAt: l.string({ format: 'datetime' }),
    samplingPerformedBy: l.optional(l.array(l.string({ format: 'did' }))),
    surveyorCount: l.optional(l.integer()),
    eventDate: l.optional(l.string()),
    eventDurationUnit: l.optional(l.string()),
    eventDurationValue: l.optional(l.integer()),
    location: l.ref<AtgeoPlace.Main>((() => AtgeoPlace.main) as any),
    track: l.optional(l.ref<Track>((() => track) as any)),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A spatial path recorded during a survey. */
type Track = {
  $type?: 'bio.cuanto.survey#track'

  /**
   * GPX 1.1 file recording the survey path.
   */
  gpx: l.BlobRef

  /**
   * Origin of the GPX file.
   */
  source: 'device' | 'uploaded' | l.UnknownString
}

export type { Track }

/** A spatial path recorded during a survey. */
const track = l.typedObject<Track>(
  $nsid,
  'track',
  l.object({
    gpx: l.blob({ accept: ['application/gpx+xml'], maxSize: 10000000 }),
    source: l.string<{ knownValues: ['device', 'uploaded'] }>(),
  }),
)

export { track }
