/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as CuantoProtocolTarget from './protocolTarget.defs.js'

const $nsid = 'bio.cuanto.surveyTarget'

type $nsid = typeof $nsid

export { $nsid }

/** A surveyor's copy of a protocol's target, created when the surveyor adopts a Protocol. Carries its own copy of the target scope so what was sought stays durable and under the surveyor's control even if the protocol author deletes the Protocol. Occurrences reference these via surveyTargetID. */
type Main = {
  $type: 'bio.cuanto.surveyTarget'

  /**
   * The Protocol this target was adopted from.
   */
  protocol: l.AtUriString

  /**
   * Provenance link to the protocol author's source protocolTarget (bio.cuanto.protocolTarget) this was copied from.
   */
  protocolTargetID: l.AtUriString

  /**
   * Client-declared timestamp when the surveyor materialized this target. Used to determine whether the surveyor knew about this target when a survey was conducted.
   */
  createdAt: l.DatetimeString

  /**
   * Timestamp when the target's source protocolTarget was removed from the protocol, after which it no longer implies a non-detection. Absent while the target is still part of the protocol.
   */
  retiredAt?: l.DatetimeString

  /**
   * One or more scope criteria copied from the source protocolTarget.
   */
  scope: (
    | l.$Typed<CuantoProtocolTarget.TaxonScope>
    | l.$Typed<CuantoProtocolTarget.VerbatimScope>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

/** A surveyor's copy of a protocol's target, created when the surveyor adopts a Protocol. Carries its own copy of the target scope so what was sought stays durable and under the surveyor's control even if the protocol author deletes the Protocol. Occurrences reference these via surveyTargetID. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    protocol: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    protocolTargetID: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    retiredAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
    scope: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<CuantoProtocolTarget.TaxonScope>(
            (() => CuantoProtocolTarget.taxonScope) as any,
          ),
          /*#__PURE__*/ l.typedRef<CuantoProtocolTarget.VerbatimScope>(
            (() => CuantoProtocolTarget.verbatimScope) as any,
          ),
        ],
        false,
      ),
      { minLength: 1 },
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
