/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtgeoPlace from '../../org/atgeo/place.defs.js'

const $nsid = 'bio.cuanto.surveyProtocol'

type $nsid = typeof $nsid

export { $nsid }

/** Defines the contents of a Survey, including what participants should look for and what fields they must fill out. */
type Main = {
  $type: 'bio.cuanto.surveyProtocol'

  /**
   * Name of the protocol (sensu DCMI dc:title).
   */
  title: string

  /**
   * Narrative description of the protocol (sensu DCMI dc:description).
   */
  description: string

  /**
   * Client-declared timestamp when this protocol was originally created.
   */
  createdAt: l.DatetimeString

  /**
   * List of fields required to complete the survey.
   */
  requiredFields?: (
    'eventDate' | 'eventDuration' | 'surveyorCount' | l.UnknownString
  )[]

  /**
   * Controlled list of locations where surveys may occur. When present, surveyors must choose from this list rather than entering a free-form location name.
   */
  locationOptions?: AtgeoPlace.Main[]
}

export type { Main }

/** Defines the contents of a Survey, including what participants should look for and what fields they must fill out. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    title: /*#__PURE__*/ l.string(),
    description: /*#__PURE__*/ l.string(),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    requiredFields: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.string<{
          knownValues: ['eventDate', 'eventDuration', 'surveyorCount']
        }>(),
      ),
    ),
    locationOptions: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<AtgeoPlace.Main>((() => AtgeoPlace.main) as any),
      ),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
