/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.js'
import * as AtgeoPlace from '../../org/atgeo/place.defs.js'

const $nsid = 'bio.cuanto.survey'

type $nsid = typeof $nsid

export { $nsid }

/** An event where participants collect data required by a Survey Protocol. */
type Main = {
  $type: 'bio.cuanto.survey'

  /**
   * Protocol followed when conducting this survey.
   */
  protocol: RepoStrongRef.Main

  /**
   * Client-declared timestamp when this survey was originally created.
   */
  createdAt: l.DatetimeString

  /**
   * DIDs of participants in addition to the record owner (sensu Humboldt eco:samplingPerformedBy).
   */
  samplingPerformedBy?: l.DidString[]

  /**
   * Total number of people conducting the Survey.
   */
  surveyorCount?: number

  /**
   * Date or datetime the survey began, ISO 8601 supporting partial forms (e.g. 2026, 2026-02, 2026-02-03, 2026-02-03T00:01:02Z).
   */
  eventDate?: string

  /**
   * Unit of eventDurationValue (sensu Humboldt eco:eventDurationUnit). Known values: 'minutes', 'hours', 'days'.
   */
  eventDurationUnit?: string

  /**
   * Duration of the survey in units specified by eventDurationUnit (sensu Humboldt eco:eventDurationValue).
   */
  eventDurationValue?: number

  /**
   * Geographic location where the survey was conducted.
   */
  location: AtgeoPlace.Main

  /**
   * A spatial path recorded during the survey.
   */
  track?: Track
}

export type { Main }

/** An event where participants collect data required by a Survey Protocol. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    protocol: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    samplingPerformedBy: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'did' })),
    ),
    surveyorCount: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
    eventDate: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    eventDurationUnit: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    eventDurationValue: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
    location: /*#__PURE__*/ l.ref<AtgeoPlace.Main>(
      (() => AtgeoPlace.main) as any,
    ),
    track: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Track>((() => track) as any),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A spatial path recorded during a survey. */
type Track = {
  $type?: 'bio.cuanto.survey#track'

  /**
   * GPX 1.1 file recording the survey path.
   */
  gpx: l.BlobRef

  /**
   * Origin of the GPX file.
   */
  source: 'device' | 'uploaded' | l.UnknownString
}

export type { Track }

/** A spatial path recorded during a survey. */
const track = /*#__PURE__*/ l.typedObject<Track>(
  $nsid,
  'track',
  /*#__PURE__*/ l.object({
    gpx: /*#__PURE__*/ l.blob({
      accept: ['application/gpx+xml'],
      maxSize: 10000000,
    }),
    source: /*#__PURE__*/ l.string<{ knownValues: ['device', 'uploaded'] }>(),
  }),
)

export { track }
