/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as CuantoProtocolTarget from './protocolTarget.defs.js'

const $nsid = 'bio.cuanto.surveyTarget'

export { $nsid }

/** A surveyor's materialized copy of a protocol's target, created when the surveyor adopts a Protocol. Carries its own copy of the target scope so what was sought stays durable and under the surveyor's control even if the protocol author deletes the Protocol. Occurrences reference these via surveyTargetID. */
type Main = {
  $type: 'bio.cuanto.surveyTarget'

  /**
   * The Protocol this target was adopted from.
   */
  protocol: l.AtUriString

  /**
   * Provenance link to the protocol author's source protocolTarget (bio.cuanto.protocolTarget) this was materialized from. May dangle if the author later deletes their target; the scope copied below remains authoritative.
   */
  protocolTargetID: l.AtUriString

  /**
   * One or more scope criteria copied from the source protocolTarget.
   */
  scope: (
    | l.$Typed<CuantoProtocolTarget.TaxonScope>
    | l.$Typed<CuantoProtocolTarget.VerbatimScope>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

/** A surveyor's materialized copy of a protocol's target, created when the surveyor adopts a Protocol. Carries its own copy of the target scope so what was sought stays durable and under the surveyor's control even if the protocol author deletes the Protocol. Occurrences reference these via surveyTargetID. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    protocol: l.string({ format: 'at-uri' }),
    protocolTargetID: l.string({ format: 'at-uri' }),
    scope: l.array(
      l.typedUnion(
        [
          l.typedRef<CuantoProtocolTarget.TaxonScope>(
            (() => CuantoProtocolTarget.taxonScope) as any,
          ),
          l.typedRef<CuantoProtocolTarget.VerbatimScope>(
            (() => CuantoProtocolTarget.verbatimScope) as any,
          ),
        ],
        false,
      ),
      { minLength: 1 },
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
