/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'community.lexicon.location.address'

export { $nsid }

/** A physical location in the form of a street address. */
type Main = {
  $type?: 'community.lexicon.location.address'

  /**
   * The ISO 3166 country code. Preferably the 2-letter code.
   */
  country: string

  /**
   * The postal code of the location.
   */
  postalCode?: string

  /**
   * The administrative region of the country. For example, a state in the USA.
   */
  region?: string

  /**
   * The locality of the region. For example, a city in the USA.
   */
  locality?: string

  /**
   * The street address.
   */
  street?: string

  /**
   * The name of the location.
   */
  name?: string
}

export type { Main }

/** A physical location in the form of a street address. */
const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    country: l.string({ minLength: 2, maxLength: 10 }),
    postalCode: l.optional(l.string()),
    region: l.optional(l.string()),
    locality: l.optional(l.string()),
    street: l.optional(l.string()),
    name: l.optional(l.string()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
