/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'community.lexicon.location.bbox'

export { $nsid }

/** A bounding box representing a rectangular geographic area defined by its corner coordinates. */
type Main = {
  $type?: 'community.lexicon.location.bbox'

  /**
   * The northern latitude boundary of the bounding box.
   */
  north: string

  /**
   * The western longitude boundary of the bounding box.
   */
  west: string

  /**
   * The southern latitude boundary of the bounding box.
   */
  south: string

  /**
   * The eastern longitude boundary of the bounding box.
   */
  east: string

  /**
   * The name of the bounding box, if any.
   */
  name?: string
}

export type { Main }

/** A bounding box representing a rectangular geographic area defined by its corner coordinates. */
const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    north: l.string(),
    west: l.string(),
    south: l.string(),
    east: l.string(),
    name: l.optional(l.string()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
