/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'community.lexicon.location.bbox'

type $nsid = typeof $nsid

export { $nsid }

/** A bounding box representing a rectangular geographic area defined by its corner coordinates. */
type Main = {
  $type?: 'community.lexicon.location.bbox'

  /**
   * The northern latitude boundary of the bounding box.
   */
  north: string

  /**
   * The western longitude boundary of the bounding box.
   */
  west: string

  /**
   * The southern latitude boundary of the bounding box.
   */
  south: string

  /**
   * The eastern longitude boundary of the bounding box.
   */
  east: string

  /**
   * The name of the bounding box, if any.
   */
  name?: string
}

export type { Main }

/** A bounding box representing a rectangular geographic area defined by its corner coordinates. */
const main = /*#__PURE__*/ l.typedObject<Main>(
  $nsid,
  'main',
  /*#__PURE__*/ l.object({
    north: /*#__PURE__*/ l.string(),
    west: /*#__PURE__*/ l.string(),
    south: /*#__PURE__*/ l.string(),
    east: /*#__PURE__*/ l.string(),
    name: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
