/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'community.lexicon.location.hthree'

export { $nsid }

/** A physical location in the form of a H3 encoded location. */
type Main = {
  $type?: 'community.lexicon.location.hthree'

  /**
   * The h3 encoded location.
   */
  value: string

  /**
   * The name of the location.
   */
  name?: string
}

export type { Main }

/** A physical location in the form of a H3 encoded location. */
const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({ value: l.string(), name: l.optional(l.string()) }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
