/// <reference lib="webworker" />
/// <reference types="@sveltejs/kit" />

import { SKIP_WAITING } from '$lib/pwa/swUpdate';
// build: hashed JS/CSS chunks generated by Vite (/_app/immutable/...)
// files: everything in static/ (icons, manifest, robots.txt, ...)
// version: changes on every deploy — used as a cache key so old caches are evicted
import { build, files, version } from '$service-worker';

// Tell TypeScript that `self` here is a ServiceWorkerGlobalScope, not a Window.
declare let self: ServiceWorkerGlobalScope;

const SHELL_CACHE = `shell-${version}`;
const PUBLIC_CACHE = 'public-pages';
const ASSETS = [...build, ...files];

async function cacheAssets(): Promise<void> {
  const cache = await caches.open(SHELL_CACHE);
  await cache.addAll(ASSETS);
  // Fetch the prerendered /app/ shell and fix it so it can be served at any
  // /app/* URL depth without breaking SvelteKit routing or asset loading.
  try {
    const res = await fetch('/app/');
    if (res.ok) {
      const html = await res.text();
      // Fix two issues so this shell works at any /app/* URL depth:
      // 1. new URL(".", location) computes the serving directory as base, which
      //    breaks SvelteKit routing when served at /app/protocols/following etc.
      //    new URL("/", location) always gives base="".
      // 2. "./_app/" references are relative to /app/ and resolve to /app/_app/
      //    (wrong). Replace with root-relative "/_app/" so assets load correctly
      //    regardless of the URL the shell is served for.
      const fixed = html
        .replace('new URL(".", location)', 'new URL("/", location)')
        .replaceAll('"./_app/', '"/_app/');
      await cache.put(
        '/app/',
        new Response(fixed, {
          headers: { 'content-type': 'text/html; charset=utf-8' },
        }),
      );
    }
  } catch {
    // Offline during install — shell will be cached on next SW update
  }
}

// 'install' fires once when the browser downloads a new version of this file.
// event.waitUntil() keeps the install phase open until the promise resolves,
// so the SW won't activate until all assets are cached.
//
// We deliberately do NOT skipWaiting() here. On an update (an old SW is still
// controlling pages) the new SW stays in 'waiting' so the old one keeps serving
// its own, still-cached JS chunks — no silently-broken navigation from evicted
// chunks (issue #4). The page prompts the user, and only when they opt in does
// it post SKIP_WAITING (below) to activate the update. On a first install there
// is no controlling SW, so the new SW activates immediately regardless.
self.addEventListener('install', (event) => {
  event.waitUntil(cacheAssets());
});

// The page posts this once the user accepts the "new version available" prompt.
// Activating here triggers 'activate' (clients.claim + cache cleanup) and a
// controllerchange in the page, which reloads to pick up the new assets.
self.addEventListener('message', (event) => {
  if ((event.data as { type?: string } | null)?.type === SKIP_WAITING) {
    self.skipWaiting();
  }
});

// 'activate' fires after install, once no older SW is controlling any pages.
// On a first install that is right away; on an update it happens only after the
// page posts SKIP_WAITING (see the message handler above), i.e. once the user
// accepts the prompt.
self.addEventListener('activate', (event) => {
  // Take control of all already-open pages in this SW's scope without waiting
  // for them to navigate. Without this, existing tabs stay under the old SW
  // until their next full navigation.
  self.clients.claim();
  // Delete caches left over from previous SW versions.
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => k !== SHELL_CACHE && k !== PUBLIC_CACHE)
            .map((k) => caches.delete(k)),
        ),
      ),
  );
});

// 'fetch' intercepts every network request made by pages this SW controls.
// Return early (no event.respondWith) to let the browser handle it normally.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  if (event.request.method !== 'GET') {
    return;
  }
  // Only handle same-origin requests; let third-party fetches pass through.
  if (url.origin !== self.location.origin) {
    return;
  }

  // Stale-while-revalidate for public protocol pages so they load from cache
  // while a fresh response arrives in the background.
  if (
    event.request.mode === 'navigate' &&
    (url.pathname === '/protocols' || url.pathname.startsWith('/protocols/'))
  ) {
    event.respondWith(staleWhileRevalidate(event.request, PUBLIC_CACHE));
    return;
  }
  if (
    (url.pathname === '/protocols' || url.pathname.startsWith('/protocols/')) &&
    url.pathname.endsWith('/__data.json')
  ) {
    event.respondWith(staleWhileRevalidate(event.request, PUBLIC_CACHE));
    return;
  }

  // Serve the cached shell for all /app/* navigations (online and offline).
  // Asset paths in the shell are rewritten to root-relative during install,
  // so it is safe to serve for any /app/* depth.
  if (
    event.request.mode === 'navigate' &&
    (url.pathname === '/app' || url.pathname.startsWith('/app/'))
  ) {
    event.respondWith(
      caches.match('/app/', { cacheName: SHELL_CACHE }).then(async (r) => {
        if (r) {
          return r;
        }
        try {
          return await fetch(event.request);
        } catch {
          // Offline and shell not yet cached (e.g. force-quit during SW
          // install). Return a minimal page so the browser does not show its
          // own offline error screen — the user can reload once back online.
          return new Response(
            '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">' +
              '<meta name="viewport" content="width=device-width,initial-scale=1">' +
              '<title>Cuanto.bio</title></head><body style="font-family:sans-serif;' +
              'text-align:center;padding:2rem"><p>You\'re offline. Reload when ' +
              'connected.</p></body></html>',
            {
              status: 200,
              headers: { 'content-type': 'text/html; charset=utf-8' },
            },
          );
        }
      }),
    );
    return;
  }

  // Cache-first for hashed static assets — they are immutable by content hash.
  if (ASSETS.includes(url.pathname)) {
    event.respondWith(
      caches.match(event.request).then((r) => r ?? fetch(event.request)),
    );
  }
});

async function staleWhileRevalidate(
  request: Request,
  cacheName: string,
): Promise<Response> {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  const networkFetch = fetch(request)
    .then((response) => {
      if (response.ok) cache.put(request, response.clone());
      return response;
    })
    .catch(() => cached ?? new Response('', { status: 503 }));
  return cached ?? networkFetch;
}
