/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'bio.lexicons.temp.v0-1.identification'

type $nsid = typeof $nsid

export { $nsid }

/** An identification suggestion for an existing observation. Used to propose or agree with a taxonomic identification. */
type Main = {
  $type: 'bio.lexicons.temp.v0-1.identification'

  /**
   * A strong reference (CID + URI) to the occurrence being identified.
   */
  occurrence: RepoStrongRef.Main

  /**
   * The full scientific name, with authorship and date information if known (Darwin Core dwc:scientificName).
   */
  scientificName: string

  /**
   * The taxonomic rank of the identification (Darwin Core dwc:taxonRank).
   */
  taxonRank?:
    | 'kingdom'
    | 'phylum'
    | 'class'
    | 'order'
    | 'family'
    | 'genus'
    | 'species'
    | 'subspecies'
    | 'variety'
    | 'form'
    | l.UnknownString

  /**
   * Taxonomic kingdom for disambiguating homonyms (Darwin Core dwc:kingdom).
   */
  kingdom?: string

  /**
   * Stable URI for the identified taxon (e.g. a GBIF species URI). Maps to Darwin Core dwc:taxonID.
   */
  taxonID?: l.UriString

  /**
   * Explanation or reasoning for this identification (Darwin Core dwc:identificationRemarks).
   */
  identificationRemarks?: string

  /**
   * Common name at time of identification.
   */
  vernacularName?: string
}

export type { Main }

/** An identification suggestion for an existing observation. Used to propose or agree with a taxonomic identification. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    occurrence: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    scientificName: /*#__PURE__*/ l.string({ maxLength: 256 }),
    taxonRank: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.withDefault(
        /*#__PURE__*/ l.string<{
          knownValues: [
            'kingdom',
            'phylum',
            'class',
            'order',
            'family',
            'genus',
            'species',
            'subspecies',
            'variety',
            'form',
          ]
          maxLength: 32
        }>({ maxLength: 32 }),
        'species',
      ),
    ),
    kingdom: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 64 }),
    ),
    taxonID: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    identificationRemarks: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 3000 }),
    ),
    vernacularName: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 256 }),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
