/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'bio.lexicons.temp.v0-1.identification'

export { $nsid }

/** An identification suggestion for an existing observation. Used to propose or agree with a taxonomic identification. */
type Main = {
  $type: 'bio.lexicons.temp.v0-1.identification'

  /**
   * A strong reference (CID + URI) to the occurrence being identified.
   */
  occurrence: RepoStrongRef.Main

  /**
   * The full scientific name, with authorship and date information if known (Darwin Core dwc:scientificName).
   */
  scientificName: string

  /**
   * The taxonomic rank of the identification (Darwin Core dwc:taxonRank).
   */
  taxonRank?:
    | 'kingdom'
    | 'phylum'
    | 'class'
    | 'order'
    | 'family'
    | 'genus'
    | 'species'
    | 'subspecies'
    | 'variety'
    | 'form'
    | l.UnknownString

  /**
   * Taxonomic kingdom for disambiguating homonyms (Darwin Core dwc:kingdom).
   */
  kingdom?: string

  /**
   * Stable URI for the identified taxon (e.g. a GBIF species URI). Maps to Darwin Core dwc:taxonID.
   */
  taxonID?: l.UriString

  /**
   * Explanation or reasoning for this identification (Darwin Core dwc:identificationRemarks).
   */
  identificationRemarks?: string

  /**
   * Common name at time of identification.
   */
  vernacularName?: string
}

export type { Main }

/** An identification suggestion for an existing observation. Used to propose or agree with a taxonomic identification. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    occurrence: l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    scientificName: l.string({ maxLength: 256 }),
    taxonRank: l.optional(
      l.withDefault(
        l.string<{
          knownValues: [
            'kingdom',
            'phylum',
            'class',
            'order',
            'family',
            'genus',
            'species',
            'subspecies',
            'variety',
            'form',
          ]
          maxLength: 32
        }>({ maxLength: 32 }),
        'species',
      ),
    ),
    kingdom: l.optional(l.string({ maxLength: 64 })),
    taxonID: l.optional(l.string({ format: 'uri' })),
    identificationRemarks: l.optional(l.string({ maxLength: 3000 })),
    vernacularName: l.optional(l.string({ maxLength: 256 })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
