/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'bio.lexicons.temp.v0-1.media'

type $nsid = typeof $nsid

export { $nsid }

/** A media record for a biodiversity observation. Stores image blobs with metadata such as alt text, aspect ratio, and license. */
type Main = {
  $type: 'bio.lexicons.temp.v0-1.media'

  /**
   * The image blob reference.
   */
  image: l.BlobRef

  /**
   * Alt text description of the image for accessibility.
   */
  alt?: string
  aspectRatio?: AspectRatio

  /**
   * SPDX license identifier for this media (maps to Dublin Core dcterms:license).
   */
  license?:
    | 'CC0-1.0'
    | 'CC-BY-4.0'
    | 'CC-BY-NC-4.0'
    | 'CC-BY-SA-4.0'
    | 'CC-BY-NC-SA-4.0'
    | l.UnknownString
}

export type { Main }

/** A media record for a biodiversity observation. Stores image blobs with metadata such as alt text, aspect ratio, and license. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    image: /*#__PURE__*/ l.blob({
      accept: ['image/jpeg', 'image/png', 'image/webp'],
      maxSize: 10000000,
    }),
    alt: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 1000 })),
    aspectRatio: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<AspectRatio>((() => aspectRatio) as any),
    ),
    license: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string<{
        knownValues: [
          'CC0-1.0',
          'CC-BY-4.0',
          'CC-BY-NC-4.0',
          'CC-BY-SA-4.0',
          'CC-BY-NC-SA-4.0',
        ]
        maxLength: 32
      }>({ maxLength: 32 }),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Width and height of an image, used for proper display before loading. */
type AspectRatio = {
  $type?: 'bio.lexicons.temp.v0-1.media#aspectRatio'
  width: number
  height: number
}

export type { AspectRatio }

/** Width and height of an image, used for proper display before loading. */
const aspectRatio = /*#__PURE__*/ l.typedObject<AspectRatio>(
  $nsid,
  'aspectRatio',
  /*#__PURE__*/ l.object({
    width: /*#__PURE__*/ l.integer({ minimum: 1 }),
    height: /*#__PURE__*/ l.integer({ minimum: 1 }),
  }),
)

export { aspectRatio }
