/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'bio.lexicons.temp.v0-1.media'

export { $nsid }

/** A media record for a biodiversity observation. Stores image blobs with metadata such as alt text, aspect ratio, and license. */
type Main = {
  $type: 'bio.lexicons.temp.v0-1.media'

  /**
   * The image blob reference.
   */
  image: l.BlobRef

  /**
   * Alt text description of the image for accessibility.
   */
  alt?: string
  aspectRatio?: AspectRatio

  /**
   * SPDX license identifier for this media (maps to Dublin Core dcterms:license).
   */
  license?:
    | 'CC0-1.0'
    | 'CC-BY-4.0'
    | 'CC-BY-NC-4.0'
    | 'CC-BY-SA-4.0'
    | 'CC-BY-NC-SA-4.0'
    | l.UnknownString
}

export type { Main }

/** A media record for a biodiversity observation. Stores image blobs with metadata such as alt text, aspect ratio, and license. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    image: l.blob({
      accept: ['image/jpeg', 'image/png', 'image/webp'],
      maxSize: 10000000,
    }),
    alt: l.optional(l.string({ maxLength: 1000 })),
    aspectRatio: l.optional(l.ref<AspectRatio>((() => aspectRatio) as any)),
    license: l.optional(
      l.string<{
        knownValues: [
          'CC0-1.0',
          'CC-BY-4.0',
          'CC-BY-NC-4.0',
          'CC-BY-SA-4.0',
          'CC-BY-NC-SA-4.0',
        ]
        maxLength: 32
      }>({ maxLength: 32 }),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Width and height of an image, used for proper display before loading. */
type AspectRatio = {
  $type?: 'bio.lexicons.temp.v0-1.media#aspectRatio'
  width: number
  height: number
}

export type { AspectRatio }

/** Width and height of an image, used for proper display before loading. */
const aspectRatio = l.typedObject<AspectRatio>(
  $nsid,
  'aspectRatio',
  l.object({
    width: l.integer({ minimum: 1 }),
    height: l.integer({ minimum: 1 }),
  }),
)

export { aspectRatio }
