/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'bio.lexicons.temp.v0-1.occurrence'

type $nsid = typeof $nsid

export { $nsid }

/** A biodiversity observation record following Darwin Core standards. Represents a single occurrence of an organism. */
type Main = {
  $type: 'bio.lexicons.temp.v0-1.occurrence'

  /**
   * The date, date-time, or interval during which the dwc:Event occurred (Darwin Core dwc:eventDate). Recommended best practice is to use a value that conforms to ISO 8601-1:2019 for single dates or date-times, or to ISO 8601-2:2019 (EDTF) for intervals and dates of reduced or uncertain precision; separate the start and end of an interval with a solidus ("/"). Include timezone information whenever a time of day is given. Examples: "1963-03-08", "1971", "1906-06", "1963-03-08T14:07:00-06:00", "1995-05-21/1995-05-23".
   */
  eventDate?: string

  /**
   * The geographic latitude in decimal degrees (Darwin Core dwc:decimalLatitude). Valid range: -90 to 90.
   */
  decimalLatitude?: string

  /**
   * The geographic longitude in decimal degrees (Darwin Core dwc:decimalLongitude). Valid range: -180 to 180.
   */
  decimalLongitude?: string

  /**
   * The horizontal distance (in meters) from the given coordinates describing the smallest circle containing the whole of the Location (Darwin Core dwc:coordinateUncertaintyInMeters).
   */
  coordinateUncertaintyInMeters?: number

  /**
   * Strong references to media records documenting the observation. Conceptually maps to the DwC-DP Occurrence Media table (https://gbif.github.io/dwc-dp/qrg/#Occurrence%20Media), which replaced the legacy dwc:associatedMedia term.
   */
  media?: RepoStrongRef.Main[]

  /**
   * Identified taxon the occurrence user has accepted, preferably a stable URI (e.g. a GBIF species URI). Derived from identification specified by acceptedIdentificationID. Must be accompanied by acceptedIdentificationID. Represents a more specific version of the DarwinCore equivalent (Darwin Core dwc:taxonID).
   */
  taxonID?: l.UriString

  /**
   * Identification accepted by the occurrence user as the source of taxonID. Must be accompanied by taxonID. Indirectly maps to Darwin Core dwc:isAcceptedIdentification.
   */
  acceptedIdentificationID?: RepoStrongRef.Main

  /**
   * The surveyor's own SurveyTarget this Occurrence was intended to satisfy. A durable, same-repo copy of the targeted criteria. Expresses observer intent. The originating ProtocolTarget is reachable via the SurveyTarget's protocolTargetID.
   */
  surveyTargetID?: l.AtUriString

  /**
   * Event (e.g. a Survey) this Occurrence was a part of (sensu DarwinCore dwc:eventID).
   */
  eventID?: l.AtUriString

  /**
   * The quantity of the organism present at the time of the Occurrence. Generally an integer or float but may be categorical, e.g. 'many' or '10-100' (sensu DarwinCore dwc:organismQuantity).
   */
  organismQuantity?: string

  /**
   * The type of quantification system used for the quantity of organisms (sensu DarwinCore dwc:organismQuantityType).
   */
  organismQuantityType?: 'individuals' | 'percent-cover' | l.UnknownString
}

export type { Main }

/** A biodiversity observation record following Darwin Core standards. Represents a single occurrence of an organism. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    eventDate: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    decimalLatitude: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    decimalLongitude: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    coordinateUncertaintyInMeters: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.integer({ minimum: 0 }),
    ),
    media: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
          (() => RepoStrongRef.main) as any,
        ),
        { maxLength: 10 },
      ),
    ),
    taxonID: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    acceptedIdentificationID: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    surveyTargetID: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'at-uri' }),
    ),
    eventID: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'at-uri' }),
    ),
    organismQuantity: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    organismQuantityType: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string<{
        knownValues: ['individuals', 'percent-cover']
      }>(),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
