/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'bio.lexicons.temp.v0-1.remark'

type $nsid = typeof $nsid

export { $nsid }

/** Free text that fills a Darwin Core remarks term on another record, such as dwc:occurrenceRemarks on an occurrence. Kept in its own record so authored prose, a potential creative work, can be attributed and licensed separately from the facts in the record it describes. The record it describes points to it with an AT-URI field named for the term (e.g. occurrence.occurrenceRemarksID), and that forward reference is authoritative: a remark nothing references fills no term. Not for discussion or replies. */
type Main = {
  $type: 'bio.lexicons.temp.v0-1.remark'

  /**
   * AT-URI of the record this remark describes, which should be the record whose forward reference points here. Lets the remark be understood and indexed on its own, and lets consumers detect a forward reference that points at the wrong remark.
   */
  subject: l.AtUriString

  /**
   * The Darwin Core term this remark fills on its subject. Should correspond to the field that references this remark, e.g. occurrenceRemarks for occurrence.occurrenceRemarksID.
   */
  dwcTerm:
    | 'occurrenceRemarks'
    | 'eventRemarks'
    | 'identificationRemarks'
    | l.UnknownString

  /**
   * The text of the remark. Becomes the value of dwcTerm when the subject is exported to Darwin Core.
   */
  body: string

  /**
   * URI of the license under which this text is published (Dublin Core dcterms:license). Creative Commons license URIs are the recommended values.
   */
  license?:
    | 'https://creativecommons.org/publicdomain/zero/1.0/'
    | 'https://creativecommons.org/licenses/by/4.0/'
    | 'https://creativecommons.org/licenses/by-nc/4.0/'
    | 'https://creativecommons.org/licenses/by-sa/4.0/'
    | 'https://creativecommons.org/licenses/by-nc-sa/4.0/'
    | l.UnknownString
}

export type { Main }

/** Free text that fills a Darwin Core remarks term on another record, such as dwc:occurrenceRemarks on an occurrence. Kept in its own record so authored prose, a potential creative work, can be attributed and licensed separately from the facts in the record it describes. The record it describes points to it with an AT-URI field named for the term (e.g. occurrence.occurrenceRemarksID), and that forward reference is authoritative: a remark nothing references fills no term. Not for discussion or replies. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    subject: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    dwcTerm: /*#__PURE__*/ l.string<{
      knownValues: [
        'occurrenceRemarks',
        'eventRemarks',
        'identificationRemarks',
      ]
      maxLength: 128
    }>({ maxLength: 128 }),
    body: /*#__PURE__*/ l.string({ maxLength: 3000 }),
    license: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string<{
        knownValues: [
          'https://creativecommons.org/publicdomain/zero/1.0/',
          'https://creativecommons.org/licenses/by/4.0/',
          'https://creativecommons.org/licenses/by-nc/4.0/',
          'https://creativecommons.org/licenses/by-sa/4.0/',
          'https://creativecommons.org/licenses/by-nc-sa/4.0/',
        ]
        maxLength: 128
      }>({ maxLength: 128 }),
    ),
  }),
)

export { main }

const $type = $nsid

type $type = typeof $type

export { $type }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
