import type { Main as AtSurveyTarget } from '$lib/lexicons/bio/cuanto/surveyTarget.defs.js';
import sql from './index.js';

export interface SurveyTargetRow {
  at_uri: string;
  rkey: string;
  protocol_uri: string;
  protocol_target_uri: string;
  record: AtSurveyTarget;
  created_at: Date | null;
  deleted_at: Date | null;
}

// rev is the repo commit revision (from a tap firehose event) that produced
// this write, if any. It's TID-ordered, so it guards against an out-of-order
// or replayed event clobbering a newer state (e.g. retired_at) with an older
// one: the upsert only applies when the incoming rev is newer than what's
// stored. Leave it undefined for writes generated by our own app code (e.g.
// materializeSurveyTargets) rather than received from the firehose -- those
// always apply, matching prior behavior.
export async function insertSurveyTarget(
  did: string,
  rkey: string,
  record: AtSurveyTarget,
  atUri: string,
  protocolTargetUri: string,
  rev?: string,
): Promise<void> {
  const targetCreatedAt = record.createdAt ? new Date(record.createdAt) : null;
  const targetRetiredAt = record.retiredAt ? new Date(record.retiredAt) : null;
  await sql`
    INSERT INTO survey_targets (
      at_uri, did, rkey, protocol_uri, protocol_target_uri, record,
      indexed_at, created_at, retired_at, rev
    )
    VALUES (
      ${atUri},
      ${did},
      ${rkey},
      ${record.protocol},
      ${protocolTargetUri},
      ${sql.json(record as Parameters<typeof sql.json>[0])},
      now(),
      ${targetCreatedAt},
      ${targetRetiredAt},
      ${rev ?? null}
    )
    ON CONFLICT (at_uri) DO UPDATE SET
      protocol_uri = EXCLUDED.protocol_uri,
      protocol_target_uri = EXCLUDED.protocol_target_uri,
      record = EXCLUDED.record,
      created_at = EXCLUDED.created_at,
      retired_at = EXCLUDED.retired_at,
      rev = EXCLUDED.rev,
      -- Clears the issue #41 tombstone: the record exists again, whether
      -- recreated by materializeSurveyTargets or by another client.
      deleted_at = NULL
    WHERE EXCLUDED.rev IS NULL
       OR survey_targets.rev IS NULL
       OR EXCLUDED.rev > survey_targets.rev
  `;
}

export async function getSurveyTargetsByDidAndProtocol(
  did: string,
  protocolUri: string,
): Promise<SurveyTargetRow[]> {
  return sql<SurveyTargetRow[]>`
    SELECT at_uri, rkey, protocol_uri, protocol_target_uri, record, created_at,
           deleted_at
    FROM survey_targets
    WHERE did = ${did} AND protocol_uri = ${protocolUri}
  `;
}

// Deletes all of a surveyor's targets for a protocol and returns their AT-URIs so
// the caller can delete the corresponding PDS records.
export async function deleteSurveyTargetsByDidAndProtocol(
  did: string,
  protocolUri: string,
): Promise<string[]> {
  const rows = await sql<{ at_uri: string }[]>`
    DELETE FROM survey_targets
    WHERE did = ${did} AND protocol_uri = ${protocolUri}
    RETURNING at_uri
  `;
  return rows.map((r) => r.at_uri);
}

// Tombstones rather than hard-deletes (issue #41). The row is what the
// occurrence export joins through and what remembers the original adoption time,
// so removing it would silently drop real detections from the export and reset
// created_at when the record is recreated. rev is the repo commit revision from
// the tap event that deleted the record; the guard mirrors insertSurveyTarget's,
// so a replayed or out-of-order delete can't re-tombstone a row a newer create
// already revived. Leave it undefined for writes generated by our own app code.
// Matching no row is not an error: gcSurveyTargetsIfUnused deletes both the row
// and the PDS record, so its delete events arrive after the row is already gone.
export async function tombstoneSurveyTargetByUri(
  atUri: string,
  rev?: string,
): Promise<void> {
  const incomingRev = rev ?? null;
  await sql`
    UPDATE survey_targets
    SET deleted_at = now(), rev = COALESCE(${incomingRev}::text, rev)
    WHERE at_uri = ${atUri}
      AND deleted_at IS NULL
      AND (
        ${incomingRev}::text IS NULL
        OR rev IS NULL
        OR ${incomingRev}::text > rev
      )
  `;
}
